package com.kairos.core.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import java.time.Instant;
import java.util.UUID;

/**
 * An abstract base class for all JPA entities in the application.
 * <p>
 * This class provides common fields that are expected in all persistent entities,
 * such as a unique identifier (ID), timestamps for creation and last update, and a version number
 * for optimistic locking.
 * </p>
 * <p>
 * By using the {@code @MappedSuperclass} annotation, JPA will include these fields in the
 * database tables of all subclasses, promoting code reuse and a consistent entity structure.
 * </p>
 */
@MappedSuperclass
@Getter
@Setter
public abstract class BaseEntity {

    /**
     * The unique identifier for the entity.
     * It is a {@link UUID} and is automatically generated by the persistence provider.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false, nullable = false)
    private UUID id;

    /**
     * The timestamp of when the entity was first created.
     * This is automatically set by Hibernate's {@code @CreationTimestamp}.
     */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false, nullable = false)
    private Instant createdAt;

    /**
     * The timestamp of when the entity was last updated.
     * This is automatically set by Hibernate's {@code @UpdateTimestamp}.
     */
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * The version number for optimistic locking.
     * This is managed by JPA to prevent concurrent modification issues.
     */
    @Version
    @Column(nullable = false)
    private int version;

}